package org.neuroph.netbeans.wizards;

import javax.swing.JTextField;

/**
 *
 * @author zoran
 */
public class NoPropVisualPanel1 extends javax.swing.JPanel {

    private static NoPropVisualPanel1 instance;
    
    /**
     * Creates new form NoPropVisualPanel1
     */
    public NoPropVisualPanel1() {
        initComponents();
    }
    
    public static NoPropVisualPanel1 getInstance(){
        if(instance==null){
            instance = new NoPropVisualPanel1();
        }
        return instance;
    }    

    public JTextField getHiddenNeuronsField() {
        return hiddenNeuronsField;
    }

    public JTextField getInputNeuronsField() {
        return inputNeuronsField;
    }

    public JTextField getOutputNeuronsField() {
        return outputNeuronsField;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inputNeuronsField = new javax.swing.JTextField();
        hiddenNeuronsField = new javax.swing.JTextField();
        outputNeuronsField = new javax.swing.JTextField();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(NoPropVisualPanel1.class, "NoPropVisualPanel1.jLabel1.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(NoPropVisualPanel1.class, "NoPropVisualPanel1.jLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(NoPropVisualPanel1.class, "NoPropVisualPanel1.jLabel3.text")); // NOI18N

        inputNeuronsField.setText(org.openide.util.NbBundle.getMessage(NoPropVisualPanel1.class, "NoPropVisualPanel1.inputNeuronsField.text")); // NOI18N

        hiddenNeuronsField.setText(org.openide.util.NbBundle.getMessage(NoPropVisualPanel1.class, "NoPropVisualPanel1.hiddenNeuronsField.text")); // NOI18N

        outputNeuronsField.setText(org.openide.util.NbBundle.getMessage(NoPropVisualPanel1.class, "NoPropVisualPanel1.outputNeuronsField.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(outputNeuronsField, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                    .addComponent(hiddenNeuronsField)
                    .addComponent(inputNeuronsField))
                .addContainerGap(171, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(inputNeuronsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(hiddenNeuronsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(outputNeuronsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(165, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField hiddenNeuronsField;
    private javax.swing.JTextField inputNeuronsField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField outputNeuronsField;
    // End of variables declaration//GEN-END:variables

    public void clearForm() {
       inputNeuronsField.setText("");
       hiddenNeuronsField.setText("");
       outputNeuronsField.setText("");
    }


}
