/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.neuroph.netbeans.wizards;

import java.awt.LayoutManager;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;

/**
 *
 * @author Stefan
 */
public class PoolingLayerPanel extends javax.swing.JPanel {

    ConvolutionalNetworkVisualPanel2 cv2;
    int j = 0;

    PoolingLayerPanel(ConvolutionalNetworkVisualPanel2 aThis, JPanel jp, int cols) {

        initComponents();

        this.cv2 = aThis;
        j = cols;
        ConvolutionalLayerPanel cp = (ConvolutionalLayerPanel) jp;
        this.jtxtNumberOfMaps.setText(cp.getJtxtNumberOfMaps().getText());
        this.jtxtKernelWidth.setText(cp.getJtxtKernelWidth().getText());
        this.jtxtKernelheight.setText(cp.getJtxtKernelheight().getText());
    }

    public PoolingLayerPanel(ConvolutionalNetworkVisualPanel2 cv2, int cols) {
        initComponents();
        this.cv2 = cv2;
        this.j = j;

    }

    public JTextField getJtxtKernelWidth() {
        return jtxtKernelWidth;
    }

    public void setJtxtKernelWidth(JTextField jtxtKernelWidth) {
        this.jtxtKernelWidth = jtxtKernelWidth;
    }

    public JTextField getJtxtKernelheight() {
        return jtxtKernelheight;
    }

    public void setJtxtKernelheight(JTextField jtxtKernelheight) {
        this.jtxtKernelheight = jtxtKernelheight;
    }

    public JTextField getJtxtNumberOfMaps() {
        return jtxtNumberOfMaps;
    }

    public void setJtxtNumberOfMaps(JTextField jtxtNumberOfMaps) {
        this.jtxtNumberOfMaps = jtxtNumberOfMaps;
    }

    /**
     * Creates new form PoolingLayerPanel
     */
    public PoolingLayerPanel() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtNumberOfMaps = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtKernelWidth = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtKernelheight = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(org.openide.util.NbBundle.getMessage(PoolingLayerPanel.class, "PoolingLayerPanel.border.title"))); // NOI18N
        setToolTipText(org.openide.util.NbBundle.getMessage(PoolingLayerPanel.class, "PoolingLayerPanel.toolTipText")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(PoolingLayerPanel.class, "PoolingLayerPanel.jLabel1.text")); // NOI18N

        jtxtNumberOfMaps.setColumns(3);
        jtxtNumberOfMaps.setText(org.openide.util.NbBundle.getMessage(PoolingLayerPanel.class, "PoolingLayerPanel.jtxtNumberOfMaps.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(PoolingLayerPanel.class, "PoolingLayerPanel.jLabel2.text")); // NOI18N

        jtxtKernelWidth.setColumns(3);
        jtxtKernelWidth.setText(org.openide.util.NbBundle.getMessage(PoolingLayerPanel.class, "PoolingLayerPanel.jtxtKernelWidth.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(PoolingLayerPanel.class, "PoolingLayerPanel.jLabel3.text")); // NOI18N

        jtxtKernelheight.setColumns(3);
        jtxtKernelheight.setText(org.openide.util.NbBundle.getMessage(PoolingLayerPanel.class, "PoolingLayerPanel.jtxtKernelheight.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jButton1, org.openide.util.NbBundle.getMessage(PoolingLayerPanel.class, "PoolingLayerPanel.jButton1.text")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxtNumberOfMaps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxtKernelWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jtxtKernelheight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtNumberOfMaps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtKernelWidth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jtxtKernelheight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(0, 10, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int z = JOptionPane.showConfirmDialog(this, "This will delete all lower layer", "Delete layers", JOptionPane.YES_NO_OPTION);
        if (z == JOptionPane.YES_OPTION) {
            int k = cv2.getPanelList().size() - 1;
            while (k >= j) {

                cv2.getPanelList().remove(k);
                k--;

            }
            cv2.deleteLayers(cv2.getPanelList());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jtxtKernelWidth;
    private javax.swing.JTextField jtxtKernelheight;
    private javax.swing.JTextField jtxtNumberOfMaps;
    // End of variables declaration//GEN-END:variables
}
