package org.neuroph.netbeans.imr.wiz;

import java.io.FileFilter;
import javax.swing.ButtonGroup;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import javax.swing.JTextField;

public final class IMRVisualPanel1 extends JPanel {

    private JFileChooser imageDirFileChooser;
    private JFileChooser junkDirFileChooser;
    /** Creates new form IMRVisualPanel1 */
    public IMRVisualPanel1() {
        initComponents();
    }

    @Override
    public String getName() {
        return "Choose folders with images";
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        colorModelButtonGroup = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        imageDirField = new javax.swing.JTextField();
        junkDirField = new javax.swing.JTextField();
        chooseImageDirButton = new javax.swing.JButton();
        chooseJunkDirButton = new javax.swing.JButton();
        colorRadioButton = new javax.swing.JRadioButton();
        bwRadioButton = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        colorModelButtonGroup.add(bwRadioButton);
        colorModelButtonGroup.add(colorRadioButton);

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(IMRVisualPanel1.class, "IMRVisualPanel1.jLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(IMRVisualPanel1.class, "IMRVisualPanel1.jLabel1.text")); // NOI18N

        imageDirField.setColumns(35);
        imageDirField.setEditable(false);

        junkDirField.setColumns(35);
        junkDirField.setEditable(false);

        org.openide.awt.Mnemonics.setLocalizedText(chooseImageDirButton, org.openide.util.NbBundle.getMessage(IMRVisualPanel1.class, "IMRVisualPanel1.chooseImageDirButton.text")); // NOI18N
        chooseImageDirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseImageDirButtonActionPerformed(evt);
            }
        });

        org.openide.awt.Mnemonics.setLocalizedText(chooseJunkDirButton, org.openide.util.NbBundle.getMessage(IMRVisualPanel1.class, "IMRVisualPanel1.chooseJunkDirButton.text")); // NOI18N
        chooseJunkDirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chooseJunkDirButtonActionPerformed(evt);
            }
        });

        colorRadioButton.setActionCommand("Color");
        org.openide.awt.Mnemonics.setLocalizedText(colorRadioButton, org.openide.util.NbBundle.getMessage(IMRVisualPanel1.class, "IMRVisualPanel1.colorRadioButton.text")); // NOI18N

        bwRadioButton.setText("BlackWhite");
        org.openide.awt.Mnemonics.setLocalizedText(bwRadioButton, org.openide.util.NbBundle.getMessage(IMRVisualPanel1.class, "IMRVisualPanel1.bwRadioButton.text")); // NOI18N

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(IMRVisualPanel1.class, "IMRVisualPanel1.jLabel3.text")); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(IMRVisualPanel1.class, "IMRVisualPanel1.jLabel4.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bwRadioButton)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(12, 12, 12)
                                .addComponent(junkDirField, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chooseJunkDirButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(imageDirField, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chooseImageDirButton)))
                        .addGap(136, 136, 136))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(colorRadioButton)
                        .addContainerGap(426, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(392, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(370, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(imageDirField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(chooseImageDirButton)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(junkDirField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chooseJunkDirButton))))
                .addGap(29, 29, 29)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(colorRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bwRadioButton)
                .addContainerGap(121, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void chooseImageDirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseImageDirButtonActionPerformed
        chooseImageDir();
}//GEN-LAST:event_chooseImageDirButtonActionPerformed

    private void chooseJunkDirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chooseJunkDirButtonActionPerformed
        chooseJunkDir();
}//GEN-LAST:event_chooseJunkDirButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bwRadioButton;
    private javax.swing.JButton chooseImageDirButton;
    private javax.swing.JButton chooseJunkDirButton;
    private javax.swing.ButtonGroup colorModelButtonGroup;
    private javax.swing.JRadioButton colorRadioButton;
    private javax.swing.JTextField imageDirField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField junkDirField;
    // End of variables declaration//GEN-END:variables

    public void chooseImageDir() {
                if (imageDirFileChooser == null) {
                    imageDirFileChooser = new JFileChooser();
                    imageDirFileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
                }

		int returnVal = imageDirFileChooser.showDialog(null, "Select Directory");
		if(returnVal == JFileChooser.APPROVE_OPTION) {
			imageDirField.setText(imageDirFileChooser.getSelectedFile().getAbsolutePath());

            
        }
    }

     public void chooseJunkDir() {
                if (junkDirFileChooser == null) {
                    junkDirFileChooser = new JFileChooser();
                    junkDirFileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
                }

		int returnVal = junkDirFileChooser.showDialog(null, "Select Directory");
		if(returnVal == JFileChooser.APPROVE_OPTION) {
			junkDirField.setText(junkDirFileChooser.getSelectedFile().getAbsolutePath());
        }
    }

    public JTextField getImageDirField() {
        return imageDirField;
    }

    public JTextField getJunkDirField() {
        return junkDirField;
    }

    public ButtonGroup getColorModelButtonGroup() {
       return colorModelButtonGroup;
    }


}

