package org.neuroph.netbeans.charts;

import org.jfree.chart.ChartPanel;
import org.netbeans.api.settings.ConvertAsProperties;
import org.neuroph.core.data.DataSet;
import org.neuroph.core.data.DataSetRow;
import org.nugs.graph2d.api.Attribute;
import org.neuroph.netbeans.charts.graphs2d.Graph2DBuilder;
import org.neuroph.netbeans.charts.graphs2d.DatasetScatter2D;
import org.neuroph.netbeans.charts.graphs2d.DatasetSeries2D;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.TopComponent;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
    dtd = "-//org.nugs.neurophgraph//VizualizeDataset2D//EN",
autostore = false)
@TopComponent.Description(
    preferredID = "VizualizeDataset2DTopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Window", id = "org.nugs.neurophgraph.VizualizeDataset2DTopComponent")
//@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
    displayName = "#CTL_VizualizeDataset2DAction",
preferredID = "VizualizeDataset2DTopComponent")
@Messages({
    "CTL_VizualizeDataset2DAction=VizualizeDataset2D",
    "CTL_VizualizeDataset2DTopComponent=Dataset visualization in 2D",
    "HINT_VizualizeDataset2DTopComponent=This is a dataset visualization in 2D window"
})
public final class VisualizeDataset2DTopComponent extends TopComponent {


    private Graph2DBuilder graphBuilder;
    String[] columnNames;
    int numInputs;

    public VisualizeDataset2DTopComponent() {
        initComponents();
        setName(Bundle.CTL_VizualizeDataset2DTopComponent());
        setToolTipText(Bundle.HINT_VizualizeDataset2DTopComponent());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        graphTypeCombo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        xCombo = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        yCombo = new javax.swing.JComboBox();
        visualizeButton = new javax.swing.JButton();
        graphPanel = new javax.swing.JPanel();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(VisualizeDataset2DTopComponent.class, "VisualizeDataset2DTopComponent.jLabel1.text")); // NOI18N

        graphTypeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(VisualizeDataset2DTopComponent.class, "VisualizeDataset2DTopComponent.jLabel2.text")); // NOI18N

        xCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(VisualizeDataset2DTopComponent.class, "VisualizeDataset2DTopComponent.jLabel3.text")); // NOI18N

        yCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        org.openide.awt.Mnemonics.setLocalizedText(visualizeButton, org.openide.util.NbBundle.getMessage(VisualizeDataset2DTopComponent.class, "VisualizeDataset2DTopComponent.visualizeButton.text")); // NOI18N
        visualizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizeButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(graphTypeCombo, 0, 152, Short.MAX_VALUE)
                    .addComponent(xCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(yCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 106, Short.MAX_VALUE))
                    .addComponent(visualizeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(graphTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(xCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(yCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(visualizeButton)
                .addContainerGap(210, Short.MAX_VALUE))
        );

        graphPanel.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(graphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(graphPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void visualizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizeButtonActionPerformed
        graphPanel.removeAll();
                        
        int xIdx = xCombo.getSelectedIndex();
        boolean isOutput;
        
        if (xIdx < numInputs) isOutput = false;
            else isOutput = true;
        
        Attribute in1 = new Attribute(xIdx, isOutput, columnNames[xIdx]);
        int yIdx = yCombo.getSelectedIndex();
        
        if (yIdx < numInputs) isOutput = false;
            else isOutput = true;
        
        Attribute in2 =new Attribute(yIdx, isOutput, columnNames[yIdx]);

        graphBuilder = (Graph2DBuilder) graphTypeCombo.getSelectedItem();
        graphBuilder.setAttribute1(in1);
        graphBuilder.setAttribute2(in2);
        ChartPanel chartPanel = graphBuilder.create();
        graphPanel.add(chartPanel);

        graphPanel.validate();
    }//GEN-LAST:event_visualizeButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel graphPanel;
    private javax.swing.JComboBox graphTypeCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton visualizeButton;
    private javax.swing.JComboBox xCombo;
    private javax.swing.JComboBox yCombo;
    // End of variables declaration//GEN-END:variables

    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    public void openChart(DataSet dataset) {
        xCombo.removeAllItems();
        yCombo.removeAllItems();

        graphTypeCombo.removeAllItems();
        
        columnNames = dataset.getColumnNames();
        numInputs = dataset.getInputSize();

        DataSetRow row = dataset.getRowAt(0);
        for (int i = 0; i < row.getInput().length; i++) {
            xCombo.addItem(columnNames[i]);
            yCombo.addItem(columnNames[i]);
        }
       
        
        for (int i = 0; i < row.getDesiredOutput().length; i++) {
            yCombo.addItem(columnNames[i+numInputs]);
            xCombo.addItem(columnNames[i+numInputs]);            
        }
        
        graphTypeCombo.addItem(new DatasetScatter2D(dataset));
        graphTypeCombo.addItem(new DatasetSeries2D(dataset));


    }
   
}
