/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.nugs.neurophgraph3d;

import org.jzy3d.chart.Chart;
import org.jzy3d.colors.colormaps.ColorMapRainbow;
import org.jzy3d.maths.Range;
import org.jzy3d.plot3d.builder.Mapper;
import org.jzy3d.plot3d.rendering.canvas.Quality;
import org.netbeans.api.settings.ConvertAsProperties;
import org.neuroph.core.NeuralNetwork;
import org.neuroph.core.Neuron;
import org.nugs.graph3d.Chart3DUtils;
import org.nugs.graph3d.Surface3DFactory;
import org.nugs.graph3d.Surface3DProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.TopComponent;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
    dtd = "-//org.nugs.neurophgraph3d//Surface//EN",
autostore = false)
@TopComponent.Description(
    preferredID = "SurfaceTopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "output", openAtStartup = false)
@ActionID(category = "Window", id = "org.nugs.neurophgraph3d.SurfaceTopComponent")
@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
    displayName = "#CTL_SurfaceAction",
preferredID = "SurfaceTopComponent")
@Messages({
    "CTL_SurfaceAction=Surface",
    "CTL_SurfaceTopComponent=Surface Window",
    "HINT_SurfaceTopComponent=This is a Surface window"
})
public final class SurfaceTopComponent extends TopComponent {

    private static SurfaceTopComponent instance;
    private NeuralNetwork nnet;
    private double[][] weights;
    private int lcount = 0; //layer count
    private int ccount = 0; // connction count

    public SurfaceTopComponent() {
        initComponents();
        setName(Bundle.CTL_SurfaceTopComponent());
        setToolTipText(Bundle.HINT_SurfaceTopComponent());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        launcherButton = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 285, Short.MAX_VALUE)
        );

        org.openide.awt.Mnemonics.setLocalizedText(launcherButton, org.openide.util.NbBundle.getMessage(SurfaceTopComponent.class, "SurfaceTopComponent.launcherButton.text")); // NOI18N
        launcherButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                launcherButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 286, Short.MAX_VALUE)
                .addComponent(launcherButton))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(launcherButton))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void launcherButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_launcherButtonActionPerformed

        Chart3DUtils.openInChartLauncher(createCustomChart(nnet));


    }//GEN-LAST:event_launcherButtonActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton launcherButton;
    // End of variables declaration//GEN-END:variables

    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    public static SurfaceTopComponent getInstance() {
        if (instance == null) {
            instance = new SurfaceTopComponent();
        }
        return instance;
    }

    private double[][] getWeights(NeuralNetwork nnet) {

        if (nnet != null) {
            lcount = nnet.getLayersCount();
            ccount = NeurophChartUtilities.getMaxConnectionCount(nnet);//prebaciti ovu metodu u klasu ChartUtilities?
            weights = new double[lcount][ccount];

            for (int i = 0; i < nnet.getLayers().length; i++) {
                for (Neuron neuron : nnet.getLayers()[i].getNeurons()) {
                    for (int j = 0; j < neuron.getInputConnections().length; j++) {
                        weights[i][j] = neuron.getInputConnections()[j].getWeight().value;
                    }
                }
            }
            return weights;
        }
        throw new RuntimeException("No neural network.");
    }

    private Chart createCustomChart(NeuralNetwork nnet) {
        this.nnet = nnet;
        weights = getWeights(nnet);

        //Biblioteka u akciji :)
        Surface3DProperties prop = new Surface3DProperties();
        prop.setChartColor(new ColorMapRainbow());
        prop.setChartQuality(Quality.Nicest);
        prop.setChartWireframed(true);

        Chart chart = Surface3DFactory.createSurface(new Mapper() {
            @Override
            public double f(double x, double y) {
                return weights[(int) x][(int) y]; //function
            }
        }, new Range(1, lcount - 1), new Range(1, ccount - 1), prop);

        chart.getAxeLayout().setXAxeLabel("Layer");
        chart.getAxeLayout().setYAxeLabel("Connection");
        chart.getAxeLayout().setZAxeLabel("Weight");
        return chart;
    }

    public void openChart(NeuralNetwork nnet) {
        Chart3DUtils.createChartPanel(createCustomChart(nnet), jPanel1);
    }
}
